#!/bin/bash

#export CC=/usr/bin/clang-7
#export CXX=/usr/bin/clang++-7

set -x

SOURCES_FOLDER="$1"
BUILD_FOLDER="$2"
BUILD_TYPE="$3" # Release/Debug
BUILD_ARCH="$4"
SOURCE_PROJECT="OpenXR-SDK-Source"
SOURCE_LOCATION="${SOURCES_FOLDER}/${SOURCE_PROJECT}"
ARM_TOOLCHAIN_ROOT="$5"

GENERATOR="Ninja"

if [ "$BUILD_ARCH" = "yocto" ] ; then
ADDITIONAL_CMAKE_PARAMS="-DCMAKE_TOOLCHAIN_FILE=/usr/local/vos-x86_64/DAQRI-VOS-Toolchain-GCC.cmake"
elif [ "$BUILD_ARCH" = "Win64" ] ; then
ADDITIONAL_CMAKE_PARAMS=""
GENERATOR="Visual Studio 15 2017 Win64"
else
ADDITIONAL_CMAKE_PARAMS=""
BUILD_ARCH="x86"
#export CC=/usr/bin/clang
#export CXX=/usr/bin/clang++
fi

BUILD_LOCATION=${BUILD_FOLDER}/${SOURCE_PROJECT}-build-${BUILD_ARCH}-${BUILD_TYPE}
INSTALL_LOCATION=${BUILD_FOLDER}/${SOURCE_PROJECT}-install-${BUILD_ARCH}-${BUILD_TYPE}
STAGING_LOCATION=${BUILD_FOLDER}/${SOURCE_PROJECT}-staging-${BUILD_ARCH}-${BUILD_TYPE}

mkdir -p "${BUILD_LOCATION}"
rm -rf "${BUILD_LOCATION}"/*
cmake -B"${BUILD_LOCATION}" -H"${SOURCE_LOCATION}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
  -G"${GENERATOR}" \
  -DCMAKE_INSTALL_PREFIX="${INSTALL_LOCATION}" \
  -DCMAKE_STAGING_PREFIX="${STAGING_LOCATION}" \
  -DBUILD_SHARED_LIBS=ON \
  ${ADDITIONAL_CMAKE_PARAMS}

#cd ${BUILD_LOCATION}
#cmake --build . --config ${BUILD_TYPE}
#cmake --build . --config ${BUILD_TYPE} --target install