#!/bin/bash

set -x

SOURCES_FOLDER="$1" # input directory (example) /e/Git/
BUILD_FOLDER="$2"   # output directory (example) /e/Git/build/
BUILD_TYPE="$3"     # Release/Debug
BUILD_ARCH="$4"     # Android/Win64/linux
SOURCE_PROJECT="magnum"
SOURCE_LOCATION="${SOURCES_FOLDER}/${SOURCE_PROJECT}"
GENERATOR="Ninja"

BUILD_LOCATION=${BUILD_FOLDER}/${SOURCE_PROJECT}-build-${BUILD_ARCH}-${BUILD_TYPE}
INSTALL_LOCATION=${BUILD_FOLDER}/install-${BUILD_ARCH}-${BUILD_TYPE}

if [ "$BUILD_ARCH" = "Android" ]; then
    BUILD_ABI="arm64-v8a" # arm64-v8a/armeabi-v7a (Android only)
    BUILD_LOCATION=${BUILD_LOCATION}-${BUILD_ABI}
fi

mkdir -p "${BUILD_LOCATION}"
rm -rf "${BUILD_LOCATION}"/*

if [ "$BUILD_ARCH" = "Android" ]; then

    ANDROID_NDK=${HOME}/AppData/Local/Android/Sdk/ndk/20.0.5594570

    ADDITIONAL_CMAKE_PARAMS=" \
        -DWITH_ANYAUDIOIMPORTER=OFF \
        -DWITH_ANYIMAGECONVERTER=ON \
        -DWITH_ANYIMAGEIMPORTER=ON \
        -DWITH_ANYSCENEIMPORTER=ON \
        -DWITH_MAGNUMFONT=ON \
        -DWITH_MAGNUMFONTCONVERTER=ON \
        -DWITH_OBJIMPORTER=ON \
        -DWITH_TGAIMAGECONVERTER=ON \
        -DWITH_TGAIMPORTER=ON \
        -DWITH_WAVAUDIOIMPORTER=OFF \
        \
        -DWITH_GL_INFO=ON \
        -DWITH_AL_INFO=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_GL_TESTS=OFF \
        \
        -DWITH_SDL2APPLICATION=OFF \
        -DWITH_ANDROIDAPPLICATION=ON \
        -DTARGET_GLES2=OFF \
        -DTARGET_GLES3=ON \
        -DBUILD_DEPRECATED=OFF \
        -DWITH_EGLCONTEXT=ON
    "

    cmake -B"${BUILD_LOCATION}" -H"${SOURCE_LOCATION}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -G"${GENERATOR}" \
        -DCMAKE_INSTALL_PREFIX="${INSTALL_LOCATION}" \
        -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK}/build/cmake/android.toolchain.cmake" \
        -DCMAKE_ANDROID_NDK="${ANDROID_NDK}" \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_SYSTEM_VERSION=26 \
        -DCMAKE_ANDROID_ARCH_ABI=${BUILD_ABI} \
        -DANDROID_NATIVE_API_LEVEL=26 \
        -DANDROID_ABI=${BUILD_ABI} \
        -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
        -DCMAKE_ANDROID_STL_TYPE=c++_static \
        -DCORRADE_RC_EXECUTABLE="/c/Corrade/bin/corrade-rc.exe" \
        -DCMAKE_FIND_ROOT_PATH="${BUILD_FOLDER}/install-${BUILD_ARCH}-${BUILD_TYPE}" \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
        ${ADDITIONAL_CMAKE_PARAMS}

elif [ "$BUILD_ARCH" = "Win64" ]; then

    GENERATOR="Visual Studio 16 2019"

    ADDITIONAL_CMAKE_PARAMS=" \
        -DWITH_WINDOWLESSWGLAPPLICATION=ON \
        -DWITH_WGLCONTEXT=ON \
        -DWITH_OPENGLTESTER=ON \
        -DWITH_ANYAUDIOIMPORTER=OFF \
        -DWITH_ANYIMAGECONVERTER=ON \
        -DWITH_ANYIMAGEIMPORTER=ON \
        -DWITH_ANYSCENEIMPORTER=ON \
        -DWITH_MAGNUMFONT=ON \
        -DWITH_MAGNUMFONTCONVERTER=ON \
        -DWITH_OBJIMPORTER=ON \
        -DWITH_TGAIMAGECONVERTER=ON \
        -DWITH_TGAIMPORTER=ON \
        -DWITH_WAVAUDIOIMPORTER=OFF \
        -DWITH_DISTANCEFIELDCONVERTER=ON \
        -DWITH_FONTCONVERTER=ON \
        -DWITH_IMAGECONVERTER=ON \
        -DWITH_GL_INFO=ON \
        -DWITH_AL_INFO=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_GL_TESTS=OFF \
        \
        -DWITH_SDL2APPLICATION=ON \
        -DWITH_GLFWAPPLICATION=OFF \
        -DTARGET_DESKTOP_GLES=OFF \
        -DTARGET_GLES=OFF \
        -DTARGET_GLES2=OFF \
    "

    cmake -B"${BUILD_LOCATION}" -H"${SOURCE_LOCATION}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -G"${GENERATOR}" \
        -DCMAKE_INSTALL_PREFIX="${INSTALL_LOCATION}" \
        -DCMAKE_PREFIX_PATH="${BUILD_FOLDER}\SDL2-2.0.10" \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="bin" \
        ${ADDITIONAL_CMAKE_PARAMS}

else #expected Linux x86

    ADDITIONAL_CMAKE_PARAMS=" \
    -DWITH_SDL2APPLICATION=ON"
    BUILD_ARCH="x86"
#export CC=/usr/bin/clang
#export CXX=/usr/bin/clang++

fi

#cd ${BUILD_LOCATION}
#cmake --build . --config ${BUILD_TYPE}
#cmake --build . --target install --config ${BUILD_TYPE}
